import { Role, RangeType } from "../globalTypes";

type SpecMetadata = {
    label: string;
    isDps: boolean;
    isHealer: boolean;
    isTank: boolean;
    image: string;
    id: number;
    role: Role;
    rangeType: RangeType;
};

export default Object.freeze({
    64: {
        label: "Frost Mage",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "mage_frost",
        id: 64,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    63: {
        label: "Fire Mage",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "mage_fire",
        id: 63,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    62: {
        label: "Arcane Mage",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "mage_arcane",
        id: 62,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    254: {
        label: "Marksmanship Hunter",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "hunter_marksmanship",
        id: 254,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    253: {
        label: "Beast Mastery Hunter",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "hunter_beastmastery",
        id: 253,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    255: {
        label: "Survival Hunter",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "hunter_survival",
        id: 255,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    105: {
        label: "Restoration Druid",
        isDps: false,
        isHealer: true,
        isTank: false,
        image: "druid_restoration",
        id: 105,
        role: "heal",
        rangeType: "ranged",
    } as SpecMetadata,
    103: {
        label: "Feral Combat Druid",
        isDps: true,
        isHealer: true,
        isTank: false,
        image: "druid_feral",
        id: 103,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    102: {
        label: "Balance Druid",
        isDps: true,
        isHealer: true,
        isTank: false,
        image: "druid_balance",
        id: 102,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,

    250: {
        label: "Blood Death Knight",
        isDps: true,
        isHealer: true,
        isTank: true,
        image: "deathknight_blood",
        id: 250,
        role: "tank",
        rangeType: "melee",
    } as SpecMetadata,

    251: {
        label: "Frost Death Knight",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "deathknight_frost",
        id: 251,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,

    252: {
        label: "Unholy Death Knight",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "deathknight_unholy",
        id: 252,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,

    65: {
        label: "Holy Paladin",
        isDps: false,
        isHealer: true,
        isTank: false,
        image: "paladin_holy",
        id: 65,
        role: "heal",
        rangeType: "ranged",
    } as SpecMetadata,
    66: {
        label: "Protection Paladin",
        isDps: true,
        isHealer: true,
        isTank: true,
        image: "paladin_protection",
        id: 66,
        role: "tank",
        rangeType: "melee",
    } as SpecMetadata,
    70: {
        label: "Retribution Paladin",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "paladin_retribution",
        id: 70,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    256: {
        label: "Discipline Priest",
        isDps: false,
        isHealer: true,
        isTank: false,
        image: "priest_discipline",
        id: 256,
        role: "heal",
        rangeType: "ranged",
    } as SpecMetadata,
    257: {
        label: "Holy Priest",
        isDps: false,
        isHealer: true,
        isTank: false,
        image: "priest_holy",
        id: 257,
        role: "heal",
        rangeType: "ranged",
    } as SpecMetadata,
    258: {
        label: "Shadow Priest",
        isDps: true,
        isHealer: true,
        isTank: false,
        image: "priest_shadow",
        id: 258,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,

    259: {
        label: "Assassination Rogue",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "rogue_assassination",
        id: 259,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    260: {
        label: "Combat Rogue",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "rogue_combat",
        id: 260,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    261: {
        label: "Subtlety Rogue",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "rogue_subtlety",
        id: 261,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    262: {
        label: "Elemental Shaman",
        isDps: true,
        isHealer: true,
        isTank: false,
        id: 262,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    263: {
        label: "Enhancement Shaman",
        isDps: true,
        isHealer: true,
        isTank: false,
        image: "shaman_enhancement",
        id: 263,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    264: {
        label: "Restoration Shaman",
        isDps: true,
        isHealer: true,
        isTank: true,
        image: "shaman_restoration",
        id: 264,
        role: "heal",
        rangeType: "ranged",
    } as SpecMetadata,

    265: {
        label: "Affliction Warlock",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "warlock_affliction",
        id: 265,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    266: {
        label: "Demonology Warlock",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "warlock_demonology",
        id: 266,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,
    267: {
        label: "Destruction Warlock",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "warlock_destruction",
        id: 267,
        role: "damage",
        rangeType: "ranged",
    } as SpecMetadata,

    71: {
        label: "Arms Warrior",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "warrior_arms",
        id: 71,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    72: {
        label: "Fury Warrior",
        isDps: true,
        isHealer: false,
        isTank: false,
        image: "warrior_fury",
        id: 72,
        role: "damage",
        rangeType: "melee",
    } as SpecMetadata,
    73: {
        label: "Protection Warrior",
        isDps: true,
        isHealer: true,
        isTank: true,
        image: "warrior_protection",
        id: 73,
        role: "tank",
        rangeType: "melee",
    } as SpecMetadata,
});
