const warrior = [
    {
        id: 103826,
        label: "Juggernaut",
        image: "ability_warrior_bullrush.png",
        row: 0,
        column: 0,
    },
    {
        id: 103827,
        label: "Double Time",
        image: "inv_misc_horn_04.png",
        row: 0,
        column: 1,
    },
    {
        id: 103828,
        label: "Warbringer",
        image: "ability_warrior_warbringer.png",
        row: 0,
        column: 2,
    },
    {
        id: 55694,
        label: "Enraged Regeneration",
        image: "ability_warrior_focusedrage.png",
        row: 1,
        column: 0,
    },
    {
        id: 29838,
        label: "Second Wind",
        image: "ability_hunter_harass.png",
        row: 1,
        column: 1,
    },
    {
        id: 103840,
        label: "Impending Victory",
        image: "spell_impending_victory.png",
        row: 1,
        column: 2,
    },
    {
        id: 107566,
        label: "Staggering Shout",
        image: "ability_bullrush.png",
        row: 2,
        column: 0,
    },
    {
        id: 12323,
        label: "Piercing Howl",
        image: "spell_shadow_deathscream.png",
        row: 2,
        column: 1,
    },
    {
        id: 102060,
        label: "Disrupting Shout",
        image: "warrior_disruptingshout.png",
        row: 2,
        column: 2,
    },
    {
        id: 46924,
        label: "Bladestorm",
        image: "ability_warrior_bladestorm.png",
        row: 3,
        column: 0,
    },
    {
        id: 46968,
        label: "Shockwave",
        image: "ability_warrior_shockwave.png",
        row: 3,
        column: 1,
    },
    {
        id: 118000,
        label: "Dragon Roar",
        image: "ability_warrior_dragonroar.png",
        row: 3,
        column: 2,
    },
    {
        id: 114028,
        label: "Mass Spell Reflection",
        image: "ability_warrior_shieldbreak.png",
        row: 4,
        column: 0,
    },
    {
        id: 114029,
        label: "Safeguard",
        image: "ability_warrior_safeguard.png",
        row: 4,
        column: 1,
    },
    {
        id: 114030,
        label: "Vigilance",
        image: "ability_warrior_vigilance.png",
        row: 4,
        column: 2,
    },
    {
        id: 107574,
        label: "Avatar",
        image: "warrior_talent_icon_avatar.png",
        row: 5,
        column: 0,
    },
    {
        id: 12292,
        label: "Bloodbath",
        image: "ability_warrior_bloodbath.png",
        row: 5,
        column: 1,
    },
    {
        id: 107570,
        label: "Storm Bolt",
        image: "warrior_talent_icon_stormbolt.png",
        row: 5,
        column: 2,
    },
] as const;

const paladin = [
    {
        id: 85499,
        label: "Speed of Light",
        image: "ability_paladin_speedoflight.png",
        row: 0,
        column: 0,
    },
    {
        id: 87172,
        label: "Long Arm of the Law",
        image: "ability_paladin_longarmofthelaw.png",
        row: 0,
        column: 1,
    },
    {
        id: 26023,
        label: "Pursuit of Justice",
        image: "ability_paladin_veneration.png",
        row: 0,
        column: 2,
    },
    {
        id: 105593,
        label: "Fist of Justice",
        image: "spell_holy_fistofjustice.png",
        row: 1,
        column: 0,
    },
    {
        id: 20066,
        label: "Repentance",
        image: "spell_holy_prayerofhealing.png",
        row: 1,
        column: 1,
    },
    {
        id: 110301,
        label: "Evil is a Point of View",
        image: "ability_paladin_turnevil.png",
        row: 1,
        column: 2,
    },
    {
        id: 85804,
        label: "Selfless Healer",
        image: "ability_paladin_gaurdedbythelight.png",
        row: 2,
        column: 0,
    },
    {
        id: 114163,
        label: "Eternal Flame",
        image: "inv_torch_thrown.png",
        row: 2,
        column: 1,
    },
    {
        id: 20925,
        label: "Sacred Shield",
        image: "ability_paladin_blessedmending.png",
        row: 2,
        column: 2,
    },
    {
        id: 114039,
        label: "Hand of Purity",
        image: "spell_holy_sealofwisdom.png",
        row: 3,
        column: 0,
    },
    {
        id: 114154,
        label: "Unbreakable Spirit",
        image: "spell_holy_unyieldingfaith.png",
        row: 3,
        column: 1,
    },
    {
        id: 105622,
        label: "Clemency",
        image: "ability_paladin_clemency.png",
        row: 3,
        column: 2,
    },
    {
        id: 105809,
        label: "Holy Avenger",
        image: "ability_paladin_holyavenger.png",
        row: 4,
        column: 0,
    },
    {
        id: 53376,
        label: "Sanctified Wrath",
        image: "ability_paladin_sanctifiedwrath.png",
        row: 4,
        column: 1,
    },
    {
        id: 86172,
        label: "Divine Purpose",
        image: "spell_holy_divinepurpose.png",
        row: 4,
        column: 2,
    },
    {
        id: 114165,
        label: "Holy Prism",
        image: "spell_paladin_holyprism.png",
        row: 5,
        column: 0,
    },
    {
        id: 114158,
        label: "Light's Hammer",
        image: "spell_paladin_lightshammer.png",
        row: 5,
        column: 1,
    },
    {
        id: 114157,
        label: "Execution Sentence",
        image: "spell_paladin_executionsentence.png",
        row: 5,
        column: 2,
    },
] as const;

const hunter = [
    {
        id: 109215,
        label: "Posthaste",
        image: "ability_hunter_posthaste.png",
        row: 0,
        column: 0,
    },
    {
        id: 109298,
        label: "Narrow Escape",
        image: "inv_misc_web_01.png",
        row: 0,
        column: 1,
    },
    {
        id: 118675,
        label: "Crouching Tiger, Hidden Chimera",
        image: "ability_hunter_pet_chimera.png",
        row: 0,
        column: 2,
    },
    {
        id: 109248,
        label: "Binding Shot",
        image: "spell_shaman_bindelemental.png",
        row: 1,
        column: 0,
    },
    {
        id: 19386,
        label: "Wyvern Sting",
        image: "inv_spear_02.png",
        row: 1,
        column: 1,
    },
    {
        id: 19577,
        label: "Intimidation",
        image: "ability_devour.png",
        row: 1,
        column: 2,
    },
    {
        id: 109304,
        label: "Exhilaration",
        image: "ability_hunter_onewithnature.png",
        row: 2,
        column: 0,
    },
    {
        id: 109260,
        label: "Aspect of the Iron Hawk",
        image: "spell_hunter_aspectoftheironhawk.png",
        row: 2,
        column: 1,
    },
    {
        id: 109212,
        label: "Spirit Bond",
        image: "ability_druid_demoralizingroar.png",
        row: 2,
        column: 2,
    },
    {
        id: 82726,
        label: "Fervor",
        image: "ability_hunter_aspectoftheviper.png",
        row: 3,
        column: 0,
    },
    {
        id: 120679,
        label: "Dire Beast",
        image: "ability_hunter_sickem.png",
        row: 3,
        column: 1,
    },
    {
        id: 109306,
        label: "Thrill of the Hunt",
        image: "ability_hunter_thrillofthehunt.png",
        row: 3,
        column: 2,
    },
    {
        id: 131894,
        label: "A Murder of Crows",
        image: "ability_hunter_murderofcrows.png",
        row: 4,
        column: 0,
    },
    {
        id: 130392,
        label: "Blink Strikes",
        image: "spell_arcane_arcane04.png",
        row: 4,
        column: 1,
    },
    {
        id: 120697,
        label: "Lynx Rush",
        image: "ability_hunter_catlikereflexes.png",
        row: 4,
        column: 2,
    },
    {
        id: 117050,
        label: "Glaive Toss",
        image: "ability_glaivetoss.png",
        row: 5,
        column: 0,
    },
    {
        id: 109259,
        label: "Powershot",
        image: "ability_hunter_resistanceisfutile.png",
        row: 5,
        column: 1,
    },
    {
        id: 120360,
        label: "Barrage",
        image: "ability_hunter_rapidregeneration.png",
        row: 5,
        column: 2,
    },
] as const;

const rogue = [
    {
        id: 14062,
        label: "Nightstalker",
        image: "ability_stealth.png",
        row: 0,
        column: 0,
    },
    {
        id: 108208,
        label: "Subterfuge",
        image: "rogue_subterfuge.png",
        row: 0,
        column: 1,
    },
    {
        id: 108209,
        label: "Shadow Focus",
        image: "rogue_shadowfocus.png",
        row: 0,
        column: 2,
    },
    {
        id: 26679,
        label: "Deadly Throw",
        image: "inv_throwingknife_06.png",
        row: 1,
        column: 0,
    },
    {
        id: 108210,
        label: "Nerve Strike",
        image: "rogue_nerve-_strike.png",
        row: 1,
        column: 1,
    },
    {
        id: 74001,
        label: "Combat Readiness",
        image: "ability_rogue_combatreadiness.png",
        row: 1,
        column: 2,
    },
    {
        id: 31230,
        label: "Cheat Death",
        image: "ability_rogue_cheatdeath.png",
        row: 2,
        column: 0,
    },
    {
        id: 108211,
        label: "Leeching Poison",
        image: "rogue_leeching_poison.png",
        row: 2,
        column: 1,
    },
    {
        id: 79008,
        label: "Elusiveness",
        image: "ability_rogue_turnthetables.png",
        row: 2,
        column: 2,
    },
    {
        id: 138106,
        label: "Cloak and Dagger",
        image: "ability_rogue_unfairadvantage.png",
        row: 3,
        column: 0,
    },
    {
        id: 36554,
        label: "Shadowstep",
        image: "ability_rogue_shadowstep.png",
        row: 3,
        column: 1,
    },
    {
        id: 108212,
        label: "Burst of Speed",
        image: "rogue_burstofspeed.png",
        row: 3,
        column: 2,
    },
    {
        id: 131511,
        label: "Prey on the Weak",
        image: "ability_rogue_preyontheweak.png",
        row: 4,
        column: 0,
    },
    {
        id: 108215,
        label: "Paralytic Poison",
        image: "rogue_paralytic_poison.png",
        row: 4,
        column: 1,
    },
    {
        id: 108216,
        label: "Dirty Tricks",
        image: "ability_rogue_dirtydeeds.png",
        row: 4,
        column: 2,
    },
    {
        id: 114014,
        label: "Shuriken Toss",
        image: "inv_throwingknife_07.png",
        row: 5,
        column: 0,
    },
    {
        id: 137619,
        label: "Marked for Death",
        image: "achievement_bg_killingblow_berserker.png",
        row: 5,
        column: 1,
    },
    {
        id: 114015,
        label: "Anticipation",
        image: "ability_rogue_slaughterfromtheshadows.png",
        row: 5,
        column: 2,
    },
] as const;

const priest = [
    {
        id: 108920,
        label: "Void Tendrils",
        image: "spell_priest_voidtendrils.png",
        row: 0,
        column: 0,
    },
    {
        id: 108921,
        label: "Psyfiend",
        image: "spell_priest_psyfiend.png",
        row: 0,
        column: 1,
    },
    {
        id: 605,
        label: "Dominate Mind",
        image: "spell_shadow_shadowworddominate.png",
        row: 0,
        column: 2,
    },
    {
        id: 64129,
        label: "Body and Soul",
        image: "spell_holy_symbolofhope.png",
        row: 1,
        column: 0,
    },
    {
        id: 121536,
        label: "Angelic Feather",
        image: "ability_priest_angelicfeather.png",
        row: 1,
        column: 1,
    },
    {
        id: 108942,
        label: "Phantasm",
        image: "ability_priest_phantasm.png",
        row: 1,
        column: 2,
    },
    {
        id: 109186,
        label: "From Darkness, Comes Light",
        image: "spell_holy_surgeoflight.png",
        row: 2,
        column: 0,
    },
    {
        id: 123040,
        label: "Mindbender",
        image: "spell_shadow_soulleech_3.png",
        row: 2,
        column: 1,
    },
    {
        id: 139139,
        label: "Solace and Insanity",
        image: "ability_priest_flashoflight.png",
        row: 2,
        column: 2,
    },
    {
        id: 19236,
        label: "Desperate Prayer",
        image: "spell_holy_testoffaith.png",
        row: 3,
        column: 0,
    },
    {
        id: 112833,
        label: "Spectral Guise",
        image: "spell_priest_spectralguise.png",
        row: 3,
        column: 1,
    },
    {
        id: 108945,
        label: "Angelic Bulwark",
        image: "ability_priest_angelicbulwark.png",
        row: 3,
        column: 2,
    },
    {
        id: 109142,
        label: "Twist of Fate",
        image: "spell_shadow_mindtwisting.png",
        row: 4,
        column: 0,
    },
    {
        id: 10060,
        label: "Power Infusion",
        image: "spell_holy_powerinfusion.png",
        row: 4,
        column: 1,
    },
    {
        id: 109175,
        label: "Divine Insight",
        image: "spell_priest_burningwill.png",
        row: 4,
        column: 2,
    },
    {
        id: 121135,
        label: "Cascade",
        image: "ability_priest_cascade.png",
        row: 5,
        column: 0,
    },
    {
        id: 110744,
        label: "Divine Star",
        image: "spell_priest_divinestar.png",
        row: 5,
        column: 1,
    },
    {
        id: 120517,
        label: "Halo",
        image: "ability_priest_halo.png",
        row: 5,
        column: 2,
    },
] as const;

const deathKnight = [
    {
        id: 108170,
        label: "Roiling Blood",
        image: "ability_deathknight_roilingblood.png",
        row: 0,
        column: 0,
    },
    {
        id: 123693,
        label: "Plague Leech",
        image: "ability_creature_disease_02.png",
        row: 0,
        column: 1,
    },
    {
        id: 115989,
        label: "Unholy Blight",
        image: "spell_shadow_contagion.png",
        row: 0,
        column: 2,
    },
    {
        id: 49039,
        label: "Lichborne",
        image: "spell_shadow_raisedead.png",
        row: 1,
        column: 0,
    },
    {
        id: 51052,
        label: "Anti-Magic Zone",
        image: "spell_deathknight_antimagiczone.png",
        row: 1,
        column: 1,
    },
    {
        id: 114556,
        label: "Purgatory",
        image: "inv_misc_shadowegg.png",
        row: 1,
        column: 2,
    },
    {
        id: 96268,
        label: "Death's Advance",
        image: "spell_shadow_demonicempathy.png",
        row: 2,
        column: 0,
    },
    {
        id: 50041,
        label: "Chilblains",
        image: "spell_frost_wisp.png",
        row: 2,
        column: 1,
    },
    {
        id: 108194,
        label: "Asphyxiate",
        image: "ability_deathknight_asphixiate.png",
        row: 2,
        column: 2,
    },
    {
        id: 48743,
        label: "Death Pact",
        image: "spell_shadow_deathpact.png",
        row: 3,
        column: 0,
    },
    {
        id: 108196,
        label: "Death Siphon",
        image: "ability_deathknight_deathsiphon.png",
        row: 3,
        column: 1,
    },
    {
        id: 119975,
        label: "Conversion",
        image: "ability_deathknight_deathsiphon2.png",
        row: 3,
        column: 2,
    },
    {
        id: 45529,
        label: "Blood Tap",
        image: "spell_deathknight_bloodtap.png",
        row: 4,
        column: 0,
    },
    {
        id: 81229,
        label: "Runic Empowerment",
        image: "inv_misc_rune_10.png",
        row: 4,
        column: 1,
    },
    {
        id: 51462,
        label: "Runic Corruption",
        image: "spell_shadow_rune.png",
        row: 4,
        column: 2,
    },
    {
        id: 108199,
        label: "Gorefiend's Grasp",
        image: "ability_deathknight_aoedeathgrip.png",
        row: 5,
        column: 0,
    },
    {
        id: 108200,
        label: "Remorseless Winter",
        image: "ability_deathknight_remorselesswinters2.png",
        row: 5,
        column: 1,
    },
    {
        id: 108201,
        label: "Desecrated Ground",
        image: "ability_deathknight_desecratedground.png",
        row: 5,
        column: 2,
    },
] as const;

const shaman = [
    {
        id: 30884,
        label: "Nature's Guardian",
        image: "spell_nature_natureguardian.png",
        row: 0,
        column: 0,
    },
    {
        id: 108270,
        label: "Stone Bulwark Totem",
        image: "ability_shaman_stonebulwark.png",
        row: 0,
        column: 1,
    },
    {
        id: 108271,
        label: "Astral Shift",
        image: "ability_shaman_astralshift.png",
        row: 0,
        column: 2,
    },
    {
        id: 63374,
        label: "Frozen Power",
        image: "spell_fire_bluecano.png",
        row: 1,
        column: 0,
    },
    {
        id: 51485,
        label: "Earthgrab Totem",
        image: "spell_nature_stranglevines.png",
        row: 1,
        column: 1,
    },
    {
        id: 108273,
        label: "Windwalk Totem",
        image: "ability_shaman_windwalktotem.png",
        row: 1,
        column: 2,
    },
    {
        id: 108285,
        label: "Call of the Elements",
        image: "ability_shaman_multitotemactivation.png",
        row: 2,
        column: 0,
    },
    {
        id: 108284,
        label: "Totemic Persistence",
        image: "ability_shaman_totemcooldownrefund.png",
        row: 2,
        column: 1,
    },
    {
        id: 108287,
        label: "Totemic Projection",
        image: "ability_shaman_totemrelocation.png",
        row: 2,
        column: 2,
    },
    {
        id: 16166,
        label: "Elemental Mastery",
        image: "spell_nature_wispheal.png",
        row: 3,
        column: 0,
    },
    {
        id: 16188,
        label: "Ancestral Swiftness",
        image: "spell_shaman_elementaloath.png",
        row: 3,
        column: 1,
    },
    {
        id: 108283,
        label: "Echo of the Elements",
        image: "ability_shaman_echooftheelements.png",
        row: 3,
        column: 2,
    },
    {
        id: 147074,
        label: "Rushing Streams",
        image: "inv_spear_04.png",
        row: 4,
        column: 0,
    },
    {
        id: 108281,
        label: "Ancestral Guidance",
        image: "ability_shaman_ancestralguidance.png",
        row: 4,
        column: 1,
    },
    {
        id: 108282,
        label: "Conductivity",
        image: "ability_shaman_fortifyingwaters.png",
        row: 4,
        column: 2,
    },
    {
        id: 117012,
        label: "Unleashed Fury",
        image: "shaman_talent_unleashedfury.png",
        row: 5,
        column: 0,
    },
    {
        id: 117013,
        label: "Primal Elementalist",
        image: "shaman_talent_primalelementalist.png",
        row: 5,
        column: 1,
    },
    {
        id: 117014,
        label: "Elemental Blast",
        image: "shaman_talent_elementalblast.png",
        row: 5,
        column: 2,
    },
] as const;

const mage = [
    {
        id: 12043,
        label: "Presence of Mind",
        image: "spell_nature_enchantarmor.png",
        row: 0,
        column: 0,
    },
    {
        id: 108843,
        label: "Blazing Speed",
        image: "spell_fire_burningspeed.png",
        row: 0,
        column: 1,
    },
    {
        id: 108839,
        label: "Ice Floes",
        image: "spell_mage_iceflows.png",
        row: 0,
        column: 2,
    },
    {
        id: 115610,
        label: "Temporal Shield",
        image: "spell_mage_temporalshield.png",
        row: 1,
        column: 0,
    },
    {
        id: 140468,
        label: "Flameglow",
        image: "inv_elemental_primal_fire.png",
        row: 1,
        column: 1,
    },
    {
        id: 11426,
        label: "Ice Barrier",
        image: "spell_ice_lament.png",
        row: 1,
        column: 2,
    },
    {
        id: 113724,
        label: "Ring of Frost",
        image: "spell_frost_ring-of-frost.png",
        row: 2,
        column: 0,
    },
    {
        id: 111264,
        label: "Ice Ward",
        image: "spell_frost_frostward.png",
        row: 2,
        column: 1,
    },
    {
        id: 102051,
        label: "Frostjaw",
        image: "ability_mage_frostjaw.png",
        row: 2,
        column: 2,
    },
    {
        id: 110959,
        label: "Greater Invisibility",
        image: "ability_mage_greaterinvisibility.png",
        row: 3,
        column: 0,
    },
    {
        id: 86949,
        label: "Cauterize",
        image: "spell_fire_rune.png",
        row: 3,
        column: 1,
    },
    {
        id: 11958,
        label: "Cold Snap",
        image: "spell_frost_wizardmark.png",
        row: 3,
        column: 2,
    },
    {
        id: 114923,
        label: "Nether Tempest",
        image: "spell_mage_nethertempest.png",
        row: 4,
        column: 0,
    },
    {
        id: 44457,
        label: "Living Bomb",
        image: "ability_mage_livingbomb.png",
        row: 4,
        column: 1,
    },
    {
        id: 112948,
        label: "Frost Bomb",
        image: "spell_mage_frostbomb.png",
        row: 4,
        column: 2,
    },
    {
        id: 114003,
        label: "Invocation",
        image: "spell_arcane_arcane03.png",
        row: 5,
        column: 0,
    },
    {
        id: 116011,
        label: "Rune of Power",
        image: "spell_mage_runeofpower.png",
        row: 5,
        column: 1,
    },
    {
        id: 1463,
        label: "Incanter's Ward",
        image: "spell_shadow_detectlesserinvisibility.png",
        row: 5,
        column: 2,
    },
] as const;
const warlock = [
    {
        id: 108359,
        label: "Dark Regeneration",
        image: "spell_warlock_darkregeneration.png",
        row: 0,
        column: 0,
    },
    {
        id: 108370,
        label: "Soul Leech",
        image: "warlock_siphonlife.png",
        row: 0,
        column: 1,
    },
    {
        id: 108371,
        label: "Harvest Life",
        image: "spell_warlock_harvestoflife.png",
        row: 0,
        column: 2,
    },
    {
        id: 47897,
        label: "Demonic Breath",
        image: "ability_warlock_shadowflame.png",
        row: 1,
        column: 0,
    },
    {
        id: 6789,
        label: "Mortal Coil",
        image: "ability_warlock_mortalcoil.png",
        row: 1,
        column: 1,
    },
    {
        id: 30283,
        label: "Shadowfury",
        image: "ability_warlock_shadowfurytga.png",
        row: 1,
        column: 2,
    },
    {
        id: 108415,
        label: "Soul Link",
        image: "ability_warlock_soullink.png",
        row: 2,
        column: 0,
    },
    {
        id: 108416,
        label: "Sacrificial Pact",
        image: "warlock_sacrificial_pact.png",
        row: 2,
        column: 1,
    },
    {
        id: 110913,
        label: "Dark Bargain",
        image: "ability_deathwing_bloodcorruption_death.png",
        row: 2,
        column: 2,
    },
    {
        id: 111397,
        label: "Blood Horror",
        image: "ability_deathwing_bloodcorruption_earth.png",
        row: 3,
        column: 0,
    },
    {
        id: 111400,
        label: "Burning Rush",
        image: "ability_deathwing_sealarmorbreachtga.png",
        row: 3,
        column: 1,
    },
    {
        id: 108482,
        label: "Unbound Will",
        image: "warlock_spelldrain.png",
        row: 3,
        column: 2,
    },
    {
        id: 108499,
        label: "Grimoire of Supremacy",
        image: "warlock_grimoireofcommand.png",
        row: 4,
        column: 0,
    },
    {
        id: 108501,
        label: "Grimoire of Service",
        image: "warlock_grimoireofservice.png",
        row: 4,
        column: 1,
    },
    {
        id: 108503,
        label: "Grimoire of Sacrifice",
        image: "warlock_grimoireofsacrifice.png",
        row: 4,
        column: 2,
    },
    {
        id: 108505,
        label: "Archimonde's Darkness",
        image: "achievement_boss_archimonde-.png",
        row: 5,
        column: 0,
    },
    {
        id: 137587,
        label: "Kil'jaeden's Cunning",
        image: "achievement_boss_kiljaedan.png",
        row: 5,
        column: 1,
    },
    {
        id: 108508,
        label: "Mannoroth's Fury",
        image: "achievement_boss_magtheridon.png",
        row: 5,
        column: 2,
    },
] as const;
const monk = [
    {
        id: 115173,
        label: "Celerity",
        image: "ability_monk_quipunch.png",
        row: 0,
        column: 0,
    },
    {
        id: 116841,
        label: "Tiger's Lust",
        image: "ability_monk_tigerslust.png",
        row: 0,
        column: 1,
    },
    {
        id: 115174,
        label: "Momentum",
        image: "ability_monk_standingkick.png",
        row: 0,
        column: 2,
    },
    {
        id: 115098,
        label: "Chi Wave",
        image: "ability_monk_chiwave.png",
        row: 1,
        column: 0,
    },
    {
        id: 124081,
        label: "Zen Sphere",
        image: "ability_monk_forcesphere.png",
        row: 1,
        column: 1,
    },
    {
        id: 123986,
        label: "Chi Burst",
        image: "spell_arcane_arcanetorrent.png",
        row: 1,
        column: 2,
    },
    {
        id: 121817,
        label: "Power Strikes",
        image: "ability_monk_powerstrikes.png",
        row: 2,
        column: 0,
    },
    {
        id: 115396,
        label: "Ascension",
        image: "ability_monk_ascension.png",
        row: 2,
        column: 1,
    },
    {
        id: 115399,
        label: "Chi Brew",
        image: "ability_monk_chibrew.png",
        row: 2,
        column: 2,
    },
    {
        id: 116844,
        label: "Ring of Peace",
        image: "spell_monk_ringofpeace.png",
        row: 3,
        column: 0,
    },
    {
        id: 119392,
        label: "Charging Ox Wave",
        image: "ability_monk_chargingoxwave.png",
        row: 3,
        column: 1,
    },
    {
        id: 119381,
        label: "Leg Sweep",
        image: "ability_monk_legsweep.png",
        row: 3,
        column: 2,
    },
    {
        id: 122280,
        label: "Healing Elixirs",
        image: "ability_monk_jasmineforcetea.png",
        row: 4,
        column: 0,
    },
    {
        id: 122278,
        label: "Dampen Harm",
        image: "ability_monk_dampenharm.png",
        row: 4,
        column: 1,
    },
    {
        id: 122783,
        label: "Diffuse Magic",
        image: "spell_monk_diffusemagic.png",
        row: 4,
        column: 2,
    },
    {
        id: 116847,
        label: "Rushing Jade Wind",
        image: "ability_monk_rushingjadewind.png",
        row: 5,
        column: 0,
    },
    {
        id: 123904,
        label: "Invoke Xuen, the White Tiger",
        image: "ability_monk_summontigerstatue.png",
        row: 5,
        column: 1,
    },
    {
        id: 115008,
        label: "Chi Torpedo",
        image: "ability_monk_quitornado.png",
        row: 5,
        column: 2,
    },
] as const;

const druid = [
    {
        id: 131768,
        label: "Feline Swiftness",
        image: "spell_druid_tirelesspursuit.png",
        row: 0,
        column: 0,
    },
    {
        id: 102280,
        label: "Displacer Beast",
        image: "spell_druid_displacement.png",
        row: 0,
        column: 1,
    },
    {
        id: 102401,
        label: "Wild Charge",
        image: "spell_druid_wildcharge.png",
        row: 0,
        column: 2,
    },
    {
        id: 145108,
        label: "Ysera's Gift",
        image: "inv_misc_head_dragon_green.png",
        row: 1,
        column: 0,
    },
    {
        id: 108238,
        label: "Renewal",
        image: "spell_nature_natureblessing.png",
        row: 1,
        column: 1,
    },
    {
        id: 102351,
        label: "Cenarion Ward",
        image: "ability_druid_naturalperfection.png",
        row: 1,
        column: 2,
    },
    {
        id: 106707,
        label: "Faerie Swarm",
        image: "spell_druid_swarm.png",
        row: 2,
        column: 0,
    },
    {
        id: 102359,
        label: "Mass Entanglement",
        image: "spell_druid_massentanglement.png",
        row: 2,
        column: 1,
    },
    {
        id: 132469,
        label: "Typhoon",
        image: "ability_druid_typhoon.png",
        row: 2,
        column: 2,
    },
    {
        id: 114107,
        label: "Soul of the Forest",
        image: "ability_druid_manatree.png",
        row: 3,
        column: 0,
    },
    {
        id: 106731,
        label: "Incarnation",
        image: "spell_druid_incarnation.png",
        row: 3,
        column: 1,
    },
    {
        id: 106737,
        label: "Force of Nature",
        image: "ability_druid_forceofnature.png",
        row: 3,
        column: 2,
    },
    {
        id: 99,
        label: "Disorienting Roar",
        image: "ability_druid_demoralizingroar.png",
        row: 4,
        column: 0,
    },
    {
        id: 102793,
        label: "Ursol's Vortex",
        image: "spell_druid_ursolsvortex.png",
        row: 4,
        column: 1,
    },
    {
        id: 5211,
        label: "Mighty Bash",
        image: "ability_druid_bash.png",
        row: 4,
        column: 2,
    },
    {
        id: 108288,
        label: "Heart of the Wild",
        image: "spell_holy_blessingofagility.png",
        row: 5,
        column: 0,
    },
    {
        id: 108373,
        label: "Dream of Cenarius",
        image: "ability_druid_dreamstate.png",
        row: 5,
        column: 1,
    },
    {
        id: 124974,
        label: "Nature's Vigil",
        image: "achievement_zone_feralas.png",
        row: 5,
        column: 2,
    },
] as const;

export default Object.freeze({
    1: warrior,
    2: paladin,
    3: hunter,
    4: rogue,
    5: priest,
    6: deathKnight,
    7: shaman,
    8: mage,
    9: warlock,
    10: monk,
    11: druid,
} as const);
